python_binary(
  name="lobsters",
  source="lobsters.py",
  dependencies=[
    "//src/python/skrode",
    "//src/python/skrode/services:lobsters",
    "//src/python:lobsters",

    # 3rdparty
    "//3rdparty/python:progressbar",
    "//3rdparty/python:requests",
  ],
)
