python_binary(
  name="imap",
  source="imap.py",
  dependencies=[
    "//src/python/skrode",
    "//src/python/skrode/services:email",
    "//src/python/skrode/imap",

    "//3rdparty/python:html2text",
  ],
)
