python_binary(
  name="ingest_directs",
  source="ingest_directs.py",
  dependencies=[
    "//src/python/skrode",
    "//src/python/skrode/redis",
    "//src/python/skrode/services:twitter",

    "//3rdparty/python:arrow",
    "//vendored/python/twitter",
  ]
)
