python_library(
  name="facebook",
  sources=["facebook.py"],
  dependencies=[
    "//src/python/skrode:schema",
    "//src/python/skrode:services",
  ]
)

python_library(
  name="github",
  sources=["github.py"],
  dependencies=[
    "//src/python/skrode:schema",
    "//src/python/skrode:services",
  ]
)

python_library(
  name="hackernews",
  sources=["hackernews.py"],
  dependencies=[
    "//src/python/skrode:schema",
    "//src/python/skrode:services",
  ]
)

python_library(
  name="keybase",
  sources=["keybase.py"],
  dependencies=[
    "//src/python/skrode:schema",
    "//src/python/skrode:services",
  ]
)

python_library(
  name="lobsters",
  sources=["lobsters.py"],
  dependencies=[
    "//src/python/skrode:schema",
    "//src/python/skrode:services",
  ]
)

python_library(
  name="reddit",
  sources=["reddit.py"],
  dependencies=[
    "//src/python/skrode:schema",
    "//src/python/skrode:services",
  ]
)

python_library(
  name="telephones",
  sources=["telephones.py"],
  dependencies=[
    "//src/python/skrode:schema",
    "//src/python/skrode:services",
  ]
)

python_library(
  name="twitter",
  sources=["twitter.py"],
  dependencies=[
    "//src/python/skrode:schema",
    "//src/python/skrode:services",
  ]
)

####################################################################################################
python_library(
  name="services",
  dependencies=[
    ":facebook",
    ":github",
    ":hackernews",
    ":keybase",
    ":lobsters",
    ":reddit",
    ":telephones",
    ":twitter",
  ]
)
