python_library(
  name="detritus",
  sources=["detritus.py"],
  dependencies=[]
)

python_library(
  name="keybase",
  sources=["keybase.py"],
  dependencies=[
    "//3rdparty/python:retrying",
    "//3rdparty/python:requests",
  ]
)

python_library(
  name="lobsters",
  sources=["lobsters.py"],
  dependencies=[
    "//3rdparty/python:beautifulsoup4",
  ]
)
