python_binary(
  name="run_topology",
  source="run_topology.py",
  dependencies=[
    # Source dependencies
    "//src/python/skrode",
    "//src/python/skrode/services",
    "//src/python/skrode/ingesters",

    # 3rdparty dependencies
    "//3rdparty/python:colorlog",
  ],
)
